/**
 * Mapping of form fields to their respective sub-steps
 * Used for granular validation and completion calculation
 */

export const PERSONAL_SUBSTEP_FIELDS: Record<number, string[]> = {
  1: [
    "student.basicInfo.firstName",
    "student.basicInfo.lastName",
    "student.basicInfo.email",
    "student.personalInfo.studentNumber",
    "student.personalInfo.course",
    "student.personalInfo.yearLevel",
    "student.personalInfo.section",
  ],
  2: [
    "student.personalInfo.suffix",
    "student.personalInfo.gender",
    "student.personalInfo.civilStatus",
    "student.personalInfo.religion",
    "student.personalInfo.dateOfBirth",
    "student.personalInfo.placeOfBirth",
    "student.personalInfo.highSchoolGWA",
    "student.personalInfo.heightM",
    "student.personalInfo.weightKg",
    "student.personalInfo.complexion",
  ],
  3: [
    "student.personalInfo.mobileNumber",
    "student.personalInfo.telephoneNumber",
    "student.addresses.0.address.region",
    "student.addresses.0.address.province",
    "student.addresses.0.address.city",
    "student.addresses.0.address.barangay",
    "student.addresses.1.address.region",
    "student.addresses.1.address.province",
    "student.addresses.1.address.city",
    "student.addresses.1.address.barangay",
    "student.personalInfo.emergencyContact.firstName",
    "student.personalInfo.emergencyContact.lastName",
    "student.personalInfo.emergencyContact.middleName",
    "student.personalInfo.emergencyContact.contactNumber",
    "student.personalInfo.emergencyContact.relationship",
    "student.personalInfo.emergencyContact.address.region",
    "student.personalInfo.emergencyContact.address.province",
    "student.personalInfo.emergencyContact.address.city",
    "student.personalInfo.emergencyContact.address.barangay",
  ],
  4: [
    "student.personalInfo.isEmployed",
    "student.personalInfo.employerName",
    "student.personalInfo.employerAddress",
    "student.personalInfo.employerContactNumber",
    "student.personalInfo.livingInDorm",
    "student.personalInfo.dormAddress",
    "student.personalInfo.landlordName",
    "student.personalInfo.landlordContactNumber",
  ],
};

export const FAMILY_SUBSTEP_FIELDS: Record<number, string[]> = {
  1: [
    "family.background.parentalStatus",
    "family.background.parentalStatusDetails",
    "family.background.haveQuietPlaceToStudy",
    "family.background.isSharingRoom",
    "family.background.roomSharingDetails",
    "family.background.natureOfResidence",
  ],
  2: [
    "family.relatedPersons.0.isLiving",
    "family.relatedPersons.0.firstName",
    "family.relatedPersons.0.middleName",
    "family.relatedPersons.0.lastName",
    "family.relatedPersons.0.dateOfBirth",
    "family.relatedPersons.0.educationalAttainment",
    "family.relatedPersons.0.occupation",
  ],
  3: [
    "family.relatedPersons.1.isLiving",
    "family.relatedPersons.1.firstName",
    "family.relatedPersons.1.middleName",
    "family.relatedPersons.1.lastName",
    "family.relatedPersons.1.dateOfBirth",
    "family.relatedPersons.1.educationalAttainment",
    "family.relatedPersons.1.occupation",
  ],
  4: [
    "family.relatedPersons.2.relationship",
    "family.relatedPersons.2.isLiving",
    "family.relatedPersons.2.firstName",
    "family.relatedPersons.2.middleName",
    "family.relatedPersons.2.lastName",
    "family.relatedPersons.2.dateOfBirth",
    "family.relatedPersons.2.occupation",
    "family.relatedPersons.2.educationalAttainment",
    "family.background.brothers",
    "family.background.sisters",
    "family.background.employedSiblings",
    "family.background.ordinalPosition",
    "family.finance.monthlyFamilyIncomeRange",
    "family.finance.monthlyFamilyIncomeRange.otherSpecification",
    "family.finance.weeklyAllowance",
    "family.finance.financialSupportTypes",
  ],
};
