/**
 * Mapping of form fields to their respective sub-steps
 * Used for granular validation and completion calculation
 */

export const PERSONAL_SUBSTEP_FIELDS: Record<number, string[]> = {
  1: [
    "student.basicInfo.firstName",
    "student.basicInfo.lastName",
    "student.basicInfo.email",
    "student.personalInfo.studentNumber",
    "student.personalInfo.course",
    "student.personalInfo.yearLevel",
    "student.personalInfo.section",
  ],
  2: [
    "student.personalInfo.suffix",
    "student.personalInfo.gender",
    "student.personalInfo.civilStatus",
    "student.personalInfo.religion",
    "student.personalInfo.dateOfBirth",
    "student.personalInfo.placeOfBirth",
    "student.personalInfo.highSchoolGWA",
    "student.personalInfo.heightFt",
    "student.personalInfo.weightKg",
    "student.personalInfo.complexion",
  ],
  3: [
    "student.personalInfo.mobileNumber",
    "student.personalInfo.telephoneNumber",
    "student.addresses.0.address.region",
    "student.addresses.0.address.province",
    "student.addresses.0.address.city",
    "student.addresses.0.address.barangay",
    "student.addresses.0.address.streetDetail",
    "student.addresses.1.address.region",
    "student.addresses.1.address.province",
    "student.addresses.1.address.city",
    "student.addresses.1.address.barangay",
    "student.addresses.1.address.streetDetail",
    "student.personalInfo.emergencyContact.firstName",
    "student.personalInfo.emergencyContact.lastName",
    "student.personalInfo.emergencyContact.middleName",
    "student.personalInfo.emergencyContact.contactNumber",
    "student.personalInfo.emergencyContact.relationship",
    "student.personalInfo.emergencyContact.address.region",
    "student.personalInfo.emergencyContact.address.province",
    "student.personalInfo.emergencyContact.address.city",
    "student.personalInfo.emergencyContact.address.barangay",
    "student.personalInfo.emergencyContact.address.streetDetail",
  ],
  4: [
    "student.personalInfo.isEmployed",
    "student.personalInfo.employerName",
    "student.personalInfo.employerAddress",
  ],
};

export const FAMILY_SUBSTEP_FIELDS: Record<number, string[]> = {
  1: [
    "family.parentalStatus",
    "family.parentalStatusDetails",
    "family.brothers",
    "family.sisters",
    "family.employedSiblings",
    "family.ordinalPosition",
    "family.haveQuietPlaceToStudy",
    "family.siblingSupportTypes",
    "family.isSharingRoom",
    "family.roomSharingDetails",
    "family.natureOfResidence",
  ],
  2: [
    "family.relatedPersons.0.isLiving",
    "family.relatedPersons.0.firstName",
    "family.relatedPersons.0.middleName",
    "family.relatedPersons.0.lastName",
    "family.relatedPersons.0.dateOfBirth",
    "family.relatedPersons.0.educationalLevel",
    "family.relatedPersons.0.occupation",
    "family.relatedPersons.0.employerName",
    "family.relatedPersons.0.employerAddress",
  ],
  3: [
    "family.relatedPersons.1.isLiving",
    "family.relatedPersons.1.firstName",
    "family.relatedPersons.1.middleName",
    "family.relatedPersons.1.lastName",
    "family.relatedPersons.1.dateOfBirth",
    "family.relatedPersons.1.educationalLevel",
    "family.relatedPersons.1.occupation",
    "family.relatedPersons.1.employerName",
    "family.relatedPersons.1.employerAddress",
  ],
  4: [
    "family.relatedPersons.2.firstName",
    "family.relatedPersons.2.middleName",
    "family.relatedPersons.2.lastName",
    "family.relatedPersons.2.dateOfBirth",
    "family.relatedPersons.2.educationalLevel",
    "family.relatedPersons.2.occupation",
    "family.relatedPersons.2.employerName",
    "family.relatedPersons.2.employerAddress",
    "family.relatedPersons.2.relationship",
  ],
};
